#!/bin/bash
#
#-----------------------------------------------------------------------------------------#
# Cisco Cloud Center Application Profile Script to build OpenStack test bed in single VM  #
# We use REL Packstack to install and configure the OpenStack bits                        #
# written by: Bill Harper																  # 
#-----------------------------------------------------------------------------------------#
#
#
#

exec > >(tee -a /usr/local/osmosix/logs/service.log) 2>&1

OSSVC_HOME=/usr/local/osmosix/service
. /usr/local/osmosix/etc/.osmosix.sh
. /usr/local/osmosix/etc/userenv
. $OSSVC_HOME/utils/cfgutil.sh
. $OSSVC_HOME/utils/install_util.sh
. $OSSVC_HOME/utils/os_info_util.sh


cmd=$1
SVCNAME="OpenStack IaaS"
SVCHOME="$OSSVC_HOME/$SVCNAME"
USER_ENV="/usr/local/osmosix/etc/userenv"

# We have done the case for "service install", "service configure", and "service start" (deploy is a dummy for now)
case $cmd in
	install)
		log "[INSTALL] Installing $SVCNAME"
		agentSendLogMessage  "Running Yum command to install OpenStack bits ..."
		# First lets install the openstack packages on this VM using yum
		sudo yum install -y centos-release-openstack-ocata
		sudo sudo yum update -y
		;;
	deploy)
		log "[DEPLOY] Deploying $SVCNAME"
		agentSendLogMessage "Running Deploy"
		;;
	configure)
	    # Now lets configure the right stuff to make OpenStack deploy using packstack
		log "[CONFIGURE] Configuring $SVCNAME"
		agentSendLogMessage  "Running Yum command to install packstack bits ..."
		sudo yum install -y openstack-packstack
		# Lets generate the packstack Answer File using packstack and then we need to customize it below
		sudo packstack --gen-answer-file=answers.txt
		agentSendLogMessage  "Running packstack to generate answers.txt file for editing ..."
		# Edit Answers file to turn on the correct OpenStack components, and set passwords, ect ...
		sed -i 's/CONFIG_DEFAULT_PASSWORD=/CONFIG_DEFAULT_PASSWORD=password/g' answers.txt
		sed -i 's/CONFIG_SWIFT_INSTALL=/CONFIG_SWIFT_INSTALL=n/g' answers.txt
		sed -i 's/CONFIG_NTP_SERVERS=/CONFIG_NTP_SERVERS=pool.ntp.org/g' answers.txt
		sed -i 's/CONFIG_KEYSTONE_ADMIN_PW=/CONFIG_KEYSTONE_ADMIN_PW=password/g' answers.txt
		sed -i 's/CONFIG_CINDER_VOLUMES_CREATE=/CONFIG_CINDER_VOLUMES_CREATE=y/g' answers.txt
		sed -i 's/CONFIG_HORIZON_SSL=/CONFIG_HORIZON_SSL=y/g' answers.txt
		sed -i 's/CONFIG_HEAT_CFN_INSTALL=/CONFIG_HEAT_CFN_INSTALL=y/g' answers.txt
		sed -i 's/CONFIG_PROVISION_DEMO=/CONFIG_PROVISION_DEMO=n/g' answers.txt
		sed -i 's/CONFIG_NEUTRON_OVS_TUNNEL_IF=/CONFIG_NEUTRON_OVS_TUNNEL_IF=eth1/g' answers.txt
		#print_log " can I see this ?"
		#print_log $cliqrNodePublicIp
		# Done Editing Answer file
		# Next we need ssh enabled for ROOT for this to work, this is needed to change the default
		sudo sed -i 's/PermitRootLogin no/PermitRootLogin yes/g' /etc/ssh/sshd_config 
		;;
	start)
		log "[START] Invoking pre-start user packstack script wait 15 minutes"
		# Next, lets start the OpenStack Installation using the modified answer file
		sudo packstack --answer-file=answers.txt
		log "[START] Starting $SVCNAME"
		log "[START] $SVCNAME successfully started."
		;;
	stop)
		log "[STOP] Invoking pre-stop user script"
		# Need some code here to remove the service completely	
		log "[STOP] Stopping $SVCNAME"
		log "[STOP] Invoking post-stop user script"
		log "[STOP] $SVCNAME successfully stopped."
		;;
	*)
		log "[ERROR] unknown command"
		exit 127
		;;
esac