#!/bin/bash

exec > >(tee -a /usr/local/osmosix/logs/service.log) 2>&1

OSSVC_HOME=/usr/local/osmosix/service
. /usr/local/osmosix/etc/.osmosix.sh
. /usr/local/osmosix/etc/userenv
. $OSSVC_HOME/utils/cfgutil.sh
. $OSSVC_HOME/utils/install_util.sh
. $OSSVC_HOME/utils/os_info_util.sh

cmd=$1
SVCNAME="openstack"
SVCHOME="$OSSVC_HOME/$SVCNAME"
USER_ENV="/usr/local/osmosix/etc/userenv"


case $cmd in
	install)
		log "[INSTALL] Installing $SVCNAME"
		yum install centos-release-openstack-ocata -y
		;;
	deploy)
		log "[DEPLOY] Deploying $SVCNAME"
		;;
	configure)
		log "[CONFIGURE] Configuring $SVCNAME"
		yum install openstack-packstack -y
		packstack --gen-answer-file=/root/answers.txt
		;;
	start)
		
		log "[START] Invoking pre-start user packstack script wait 15 minutes"
		packstack --answer-file=/root/answers.txt
		log "[START] Starting $SVCNAME"
		log "[START] $SVCNAME successfully started."
		;;
	stop)
		log "[STOP] Invoking pre-stop user script"		
		log "[STOP] Stopping $SVCNAME"
		log "[STOP] Invoking post-stop user script"
		log "[STOP] $SVCNAME successfully stopped."
		;;
	*)
		log "[ERROR] unknown command"
		exit 127
		;;
esac